<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
                              
<div>
    <h1>Welcome to NemonicWeb</h1>

    <p> We are in the
    <?php 
        echo APPLICATION_ENV;
    ?>
    environment.
    </p>                          
                              
    <p>
        Friend names are
    <?php foreach ($this->entries as $entry): ?>
            <dt><?php echo $this->escape($entry->name) ?></dt>
            <dd><?php echo $this->escape($entry->dateCreated) ?></dd>
    <?php endforeach ?>
      
    </p>
 

</div>